# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            CloudLander
tagline:          Simple Blog
url:              http://cloudlander.github.io
paginate:         1
baseurl:          /
author:
  name:           cloudlander
  url:            http://cloudlander.github.io
  email:          zhangxiaomin@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/cloudlander/cloudlander.github.io.git

pages_list:       
  About:        '/about'
  Archive:      '/archive'
  Feed:         '/atom.xml'

